### ISSUE TITLE
Running on random uniform ensemble example

### ISSUE THREAD

**Issue by youngseok-kim** [stephenslab/mixsqp#13]
Would it be okay to add sufficient decrease param? or I don't really wanted to stop the algorithm if line search is failed after 10 trials. It would be better to continue and see what's going on in the next 10 steps.

```R
set.seed(1)
L <- matrix(runif(100000 * 20), ncol = 20)
x_true <- mixsqp(L, control = list(eps = 1e-4, convtol.sqp = 1e-4))
```

**Comment by pcarbo** [comment]
@youngseok-kim Please try it again. I changed the minimum step size to `0.5^23 = 1.2e-7`.

**Comment by youngseok-kim** [comment]
Thank you, it worked.
