### ISSUE TITLE
Make backtracking line search more customizable

### ISSUE THREAD

**Issue by pcarbo** [stephenslab/mixsqp#21]
Currently, the backtracking line search settings are hard-coded (e.g., "rho" is set to 0.5). We should allow the user to adjust these settings, e.g., following the setup used in Algorithm 3.1 of Nocedal & Wright, 2nd ed. These improvements will be developed in the `better-line-search` branch.

**Comment by youngseok-kim** [comment]
Please see linesearch branch

**Comment by pcarbo** [comment]
@youngseok-kim Could you please change the code in `backtrackinglinesearch` so that:

1. You keep track of the step size, and provide it as a return value.

2. You have a minimum step size parameter, e.g., `min.step.size`, and the line search stops when the step size is less than this.
