### ISSUE TITLE
Add "log" argument to mixsqp interface

### ISSUE THREAD

**Issue by halasadi** [stephenslab/mixsqp#34]
Peter asked me to post this as an issue,

> Used you guys' R package for speeding up an algorithm that uses empirical Bayes. Sped up the prior estimation by 100x. Easy to use and gave same results as previous algorithm.
> I have a log-likelihood matrix but your package requires likelihood matrices (non-negative entries) so just had to do a pre-processing step:

` L <- exp(logL - matrixStats::rowMaxs(logL))`
> Might be worth adding to the vignette?

**Comment by pcarbo** [comment]
Thanks @halasadi. It makes me think that we should have a small vignette demonstrating how `mixsqp` can be used to fit a mixture model (e.g., a mixture of normals), giving the likelihood calculations, etc.

**Comment by halasadi** [comment]
Yes, probably a good idea. I think for me what's important is to make sure you don't have a loss of numerical precision when converting from log-likelihood to likelihood (hence why I computed the likelihood relative to the max. likelihood in that row)

**Comment by stephens999** [comment]
yes i think hussein's point is how to reliably apply mixsqp to log-likelihoods 

an option to consider: we could add a flag `loglik=TRUE/FALSE` to deal with this internally...

**Comment by pcarbo** [comment]
That is an approach to consider, although I hesistate to call the  `L` argument the "likelihood" since it could be something else.

**Comment by pcarbo** [comment]
@halasadi @stephens999 I added a "log" argument to `mixsqp` in commit 590595f.
