### ISSUE TITLE
unused variable warning during installation

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/mixsqp#36]
Installing the latest version (0.3.9) generates this warning:

```
mixsqp.cpp:53:7: warning: unused variable 'n' [-Wunused-variable]
  int n = L.n_rows;
      ^
1 warning generated.
```

**Comment by pcarbo** [comment]
@willwerscheid Thanks for the bug report. Can you please try again and let me know if there are further warnings? I will close this issue but please re-open if needed.

**Comment by willwerscheid** [comment]
Looks good.
