### ISSUE TITLE
Not available to install from CRAN

### ISSUE THREAD

**Issue by halasadi** [stephenslab/mixsqp#37]
Just FYI (in case you don't already know),

Seems like the package was removed from CRAN, see here

https://cloud.r-project.org/web/packages/mixsqp/index.html

Hussein

**Comment by pcarbo** [comment]
@halasadi Thanks---I'm working on it.

A downside of CRAN is that it will sometimes remove your packages without warning or explanation.

**Comment by pcarbo** [comment]
@halasadi The mixsqp package is back on CRAN.
