### ISSUE TITLE
"Missing value" error

### ISSUE THREAD

**Issue by willwerscheid** [stephenslab/mixsqp#39]
I get the following error in `mixsqp`:

```
Error in if (all(y > 0)) return(-sum(w * (z + log(y)))) else return(Inf) : 
  missing value where TRUE/FALSE needed
```

See Slack for a reproducible example.

**Comment by pcarbo** [comment]
@willwerscheid Can you please try again with the latest version of mixsqp? There is an issue with the EM updates in which in very rare cases they will result in non-finite mixture weights (Inf or NaN). It should be fixed now.

**Comment by willwerscheid** [comment]
Works great -- thanks @pcarbo !
